Optimizations, new option, code improvements.
nomakewan/BackToTheFutureV pull request #1
Opened 2022-10-11 04:06 UTC by AyeItsAxi

Replaced most if statement terror with switch statements, added extra option to prevent lightning from breaking time circuits and hover capabilities with help from nomakewan. General optimizations and cleaner code in some files.

2022-10-11 17:55 UTC, VictorGamer072YT commented
rip git commit names

2022-10-11 17:57 UTC, VictorGamer072YT requested changes
Both commit ([1e2ad42](https://github.com/nomakewan/BackToTheFutureV/pull/1/commits/1e2ad42b65bee569f10fc34658f3aed0f33f4eba)) and [2b6f3f9](https://github.com/nomakewan/BackToTheFutureV/pull/1/commits/2b6f3f9da5d6ff55548b842d95ac0af19a58c353) are useless. I suggest pulling the origin before making a PR.
Commit names might be useful to change, too.

The plutonium buy limit. Just, why?

Avoid modifying the .csproj for no reason, specifically in [7d1623f](https://github.com/nomakewan/BackToTheFutureV/pull/1/commits/7d1623fd9f9aef13e484d56189377ecfdb4d6de2).

Commit [3e59c2c](https://github.com/nomakewan/BackToTheFutureV/pull/1/commits/3e59c2c0dd1e2b23587b35a9ca1eb1b878f88cc7) could be merged with [7d1623f](https://github.com/nomakewan/BackToTheFutureV/pull/1/commits/7d1623fd9f9aef13e484d56189377ecfdb4d6de2).

The actual if -> switch part looks fine, though.
But as ran said earlier, is there truly a reason to refactor this? Besides improving reading a bit, it doesn't really do much.

2022-10-11 18:10 UTC, VictorGamer072YT commented
Also, I have no clue on how github's review system works, so ignore that.

2022-10-11 18:11 UTC, VictorGamer072YT commented on BackToTheFutureV/Menu/GarageMenu.cs
> +            buyPlutonium.Enabled = FusionUtils.CurrentTime.Year > 1985 && FusionUtils.CurrentTime.Year < 2015;
Just, why?

2022-10-12 10:37 UTC, ranstar74 commented
[2b6f3f9](https://github.com/nomakewan/BackToTheFutureV/pull/1/commits/2b6f3f9da5d6ff55548b842d95ac0af19a58c353) breaks relative dependency paths in project file

2022-10-12 18:39 UTC, closed without merging